FROM jupyter/minimal-notebook:latest 
USER root
ENV GRANT_SUDO="yes"
COPY ./.bashrc /opt/conda/
RUN cat /opt/conda/.bashrc >> /etc/bash.bashrc

# USER ${NB_UID}
WORKDIR /home/jovyan

RUN conda install --quiet --yes nb_conda_kernels \ 
    && conda create --quiet --yes --name test-env python=3.7 

SHELL ["conda", "run", "-n", "etl", "/bin/bash", "-c"]
#jupyter kernelspec uninstall python3 

RUN conda install --quiet --yes ipykernel \
    && ipython kernel install --user --name=test-env --display-name "Python (test-env)"
